### ISSUE TITLE
Enable ParserTests on travis

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/Fission#107]
Travis doesn't run ParserTests. It should. One of the tests are failing, probably due to refactorings by @rachitnigam.

**Comment by rachitnigam** [comment]
Yeah, `sub`is now desugared into function application instead of an op. 

The reason ParserTests are not enabled on travis is because they were mostly useful when I was trying to write the parser itself. 

The other tests kind of subsume it. Also, I don't want travis spinning up 5 workers for every commit.
